# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/DlgQueryBuilder.ui'
#
# Created: Mon Feb 21 13:52:59 2011
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(774, 603)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        Dialog.setFont(font)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fileEdit = QtGui.QLineEdit(self.groupBox)
        self.fileEdit.setReadOnly(True)
        self.fileEdit.setObjectName("fileEdit")
        self.gridLayout_4.addWidget(self.fileEdit, 0, 1, 1, 1)
        self.openFileBtn = QtGui.QPushButton(self.groupBox)
        self.openFileBtn.setObjectName("openFileBtn")
        self.gridLayout_4.addWidget(self.openFileBtn, 0, 2, 1, 1)
        self.queriesCombo = QtGui.QComboBox(self.groupBox)
        self.queriesCombo.setObjectName("queriesCombo")
        self.gridLayout_4.addWidget(self.queriesCombo, 1, 0, 1, 2)
        self.loadQueryBtn = QtGui.QPushButton(self.groupBox)
        self.loadQueryBtn.setObjectName("loadQueryBtn")
        self.gridLayout_4.addWidget(self.loadQueryBtn, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.toolBox = QtGui.QToolBox(Dialog)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 230))
        self.toolBox.setFrameShape(QtGui.QFrame.Panel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Sunken)
        self.toolBox.setObjectName("toolBox")
        self.page_1 = QtGui.QWidget()
        self.page_1.setGeometry(QtCore.QRect(0, 0, 754, 156))
        self.page_1.setObjectName("page_1")
        self.horizontalLayout = QtGui.QHBoxLayout(self.page_1)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tablesTree = QtGui.QTreeView(self.page_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tablesTree.sizePolicy().hasHeightForWidth())
        self.tablesTree.setSizePolicy(sizePolicy)
        self.tablesTree.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablesTree.setObjectName("tablesTree")
        self.horizontalLayout.addWidget(self.tablesTree)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.joinBtn = QtGui.QPushButton(self.page_1)
        self.joinBtn.setObjectName("joinBtn")
        self.gridLayout_3.addWidget(self.joinBtn, 0, 0, 1, 1)
        self.inTableBtn = QtGui.QPushButton(self.page_1)
        self.inTableBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.inTableBtn.setObjectName("inTableBtn")
        self.gridLayout_3.addWidget(self.inTableBtn, 0, 1, 1, 1)
        self.innerJoinBtn = QtGui.QPushButton(self.page_1)
        self.innerJoinBtn.setObjectName("innerJoinBtn")
        self.gridLayout_3.addWidget(self.innerJoinBtn, 1, 0, 1, 1)
        self.outTableBtn = QtGui.QPushButton(self.page_1)
        self.outTableBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.outTableBtn.setObjectName("outTableBtn")
        self.gridLayout_3.addWidget(self.outTableBtn, 1, 1, 1, 1)
        self.outerJoinBtn = QtGui.QPushButton(self.page_1)
        self.outerJoinBtn.setObjectName("outerJoinBtn")
        self.gridLayout_3.addWidget(self.outerJoinBtn, 2, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.tablesList = QtGui.QListWidget(self.page_1)
        self.tablesList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablesList.setAlternatingRowColors(True)
        self.tablesList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tablesList.setObjectName("tablesList")
        QtGui.QListWidgetItem(self.tablesList)
        QtGui.QListWidgetItem(self.tablesList)
        self.horizontalLayout.addWidget(self.tablesList)
        self.toolBox.addItem(self.page_1, "")
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 754, 156))
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fieldsTree = QtGui.QTreeWidget(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.fieldsTree.sizePolicy().hasHeightForWidth())
        self.fieldsTree.setSizePolicy(sizePolicy)
        self.fieldsTree.setObjectName("fieldsTree")
        item_0 = QtGui.QTreeWidgetItem(self.fieldsTree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.fieldsTree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.horizontalLayout_2.addWidget(self.fieldsTree)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem2 = QtGui.QSpacerItem(67, 19, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.inFieldBtn = QtGui.QPushButton(self.page_2)
        self.inFieldBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.inFieldBtn.setObjectName("inFieldBtn")
        self.gridLayout_2.addWidget(self.inFieldBtn, 0, 0, 1, 1)
        self.outFieldBtn = QtGui.QPushButton(self.page_2)
        self.outFieldBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.outFieldBtn.setObjectName("outFieldBtn")
        self.gridLayout_2.addWidget(self.outFieldBtn, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        spacerItem3 = QtGui.QSpacerItem(67, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.fieldsList = QtGui.QListWidget(self.page_2)
        self.fieldsList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.fieldsList.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.fieldsList.setAlternatingRowColors(True)
        self.fieldsList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.fieldsList.setObjectName("fieldsList")
        QtGui.QListWidgetItem(self.fieldsList)
        QtGui.QListWidgetItem(self.fieldsList)
        QtGui.QListWidgetItem(self.fieldsList)
        self.horizontalLayout_2.addWidget(self.fieldsList)
        self.toolBox.addItem(self.page_2, "")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 754, 156))
        self.page.setObjectName("page")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fieldsCondTree = QtGui.QTreeWidget(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.fieldsCondTree.sizePolicy().hasHeightForWidth())
        self.fieldsCondTree.setSizePolicy(sizePolicy)
        self.fieldsCondTree.setObjectName("fieldsCondTree")
        item_0 = QtGui.QTreeWidgetItem(self.fieldsCondTree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.fieldsCondTree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.horizontalLayout_5.addWidget(self.fieldsCondTree)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.eqBtn = QtGui.QPushButton(self.page)
        self.eqBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.eqBtn.setObjectName("eqBtn")
        self.gridLayout.addWidget(self.eqBtn, 0, 0, 1, 1)
        self.ltBtn = QtGui.QPushButton(self.page)
        self.ltBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.ltBtn.setObjectName("ltBtn")
        self.gridLayout.addWidget(self.ltBtn, 0, 1, 1, 1)
        self.gtBtn = QtGui.QPushButton(self.page)
        self.gtBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gtBtn.setObjectName("gtBtn")
        self.gridLayout.addWidget(self.gtBtn, 0, 2, 1, 1)
        self.inBtn = QtGui.QPushButton(self.page)
        self.inBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.inBtn.setObjectName("inBtn")
        self.gridLayout.addWidget(self.inBtn, 0, 3, 1, 1)
        self.neqBtn = QtGui.QPushButton(self.page)
        self.neqBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.neqBtn.setObjectName("neqBtn")
        self.gridLayout.addWidget(self.neqBtn, 1, 0, 1, 1)
        self.lteBtn = QtGui.QPushButton(self.page)
        self.lteBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lteBtn.setObjectName("lteBtn")
        self.gridLayout.addWidget(self.lteBtn, 1, 1, 1, 1)
        self.gteBtn = QtGui.QPushButton(self.page)
        self.gteBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gteBtn.setObjectName("gteBtn")
        self.gridLayout.addWidget(self.gteBtn, 1, 2, 1, 1)
        self.ninBtn = QtGui.QPushButton(self.page)
        self.ninBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.ninBtn.setObjectName("ninBtn")
        self.gridLayout.addWidget(self.ninBtn, 1, 3, 1, 1)
        self.andBtn = QtGui.QPushButton(self.page)
        self.andBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.andBtn.setObjectName("andBtn")
        self.gridLayout.addWidget(self.andBtn, 2, 0, 1, 1)
        self.orBtn = QtGui.QPushButton(self.page)
        self.orBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.orBtn.setObjectName("orBtn")
        self.gridLayout.addWidget(self.orBtn, 2, 1, 1, 1)
        self.notBtn = QtGui.QPushButton(self.page)
        self.notBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.notBtn.setObjectName("notBtn")
        self.gridLayout.addWidget(self.notBtn, 2, 2, 1, 1)
        self.likeBtn = QtGui.QPushButton(self.page)
        self.likeBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.likeBtn.setObjectName("likeBtn")
        self.gridLayout.addWidget(self.likeBtn, 3, 0, 1, 1)
        self.ilikeBtn = QtGui.QPushButton(self.page)
        self.ilikeBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.ilikeBtn.setObjectName("ilikeBtn")
        self.gridLayout.addWidget(self.ilikeBtn, 3, 1, 1, 1)
        self.percBtn = QtGui.QPushButton(self.page)
        self.percBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.percBtn.setObjectName("percBtn")
        self.gridLayout.addWidget(self.percBtn, 3, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.valueEdit = QtGui.QLineEdit(self.page)
        self.valueEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.valueEdit.setObjectName("valueEdit")
        self.verticalLayout_2.addWidget(self.valueEdit)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.inValueBtn = QtGui.QToolButton(self.page)
        self.inValueBtn.setObjectName("inValueBtn")
        self.horizontalLayout_3.addWidget(self.inValueBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtGui.QSpacerItem(147, 37, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.toolBox.addItem(self.page, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.queryBrowser = QtGui.QPlainTextEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryBrowser.sizePolicy().hasHeightForWidth())
        self.queryBrowser.setSizePolicy(sizePolicy)
        self.queryBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.queryBrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.queryBrowser.setObjectName("queryBrowser")
        self.verticalLayout.addWidget(self.queryBrowser)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.geomCombo = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geomCombo.sizePolicy().hasHeightForWidth())
        self.geomCombo.setSizePolicy(sizePolicy)
        self.geomCombo.setEditable(True)
        self.geomCombo.setObjectName("geomCombo")
        self.horizontalLayout_6.addWidget(self.geomCombo)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.uniqueCombo = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uniqueCombo.sizePolicy().hasHeightForWidth())
        self.uniqueCombo.setSizePolicy(sizePolicy)
        self.uniqueCombo.setEditable(True)
        self.uniqueCombo.setObjectName("uniqueCombo")
        self.horizontalLayout_6.addWidget(self.uniqueCombo)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.getColumnsBtn = QtGui.QPushButton(self.groupBox_3)
        self.getColumnsBtn.setObjectName("getColumnsBtn")
        self.horizontalLayout_6.addWidget(self.getColumnsBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.clearBtn = QtGui.QPushButton(Dialog)
        self.clearBtn.setObjectName("clearBtn")
        self.horizontalLayout_4.addWidget(self.clearBtn)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.saveQueryCheck = QtGui.QCheckBox(Dialog)
        self.saveQueryCheck.setChecked(False)
        self.saveQueryCheck.setObjectName("saveQueryCheck")
        self.horizontalLayout_4.addWidget(self.saveQueryCheck)
        self.queryNameEdit = QtGui.QLineEdit(Dialog)
        self.queryNameEdit.setObjectName("queryNameEdit")
        self.horizontalLayout_4.addWidget(self.queryNameEdit)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.label_2.setBuddy(self.openFileBtn)
        self.label_3.setBuddy(self.geomCombo)
        self.label_4.setBuddy(self.uniqueCombo)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(2)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Query Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Stored query", None, QtGui.QApplication.UnicodeUTF8))
        self.openFileBtn.setText(QtGui.QApplication.translate("Dialog", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.loadQueryBtn.setText(QtGui.QApplication.translate("Dialog", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Queries file:", None, QtGui.QApplication.UnicodeUTF8))
        self.joinBtn.setText(QtGui.QApplication.translate("Dialog", "JOIN", None, QtGui.QApplication.UnicodeUTF8))
        self.inTableBtn.setText(QtGui.QApplication.translate("Dialog", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.innerJoinBtn.setText(QtGui.QApplication.translate("Dialog", "INNER JOIN", None, QtGui.QApplication.UnicodeUTF8))
        self.outTableBtn.setText(QtGui.QApplication.translate("Dialog", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.outerJoinBtn.setText(QtGui.QApplication.translate("Dialog", "OUTER JOIN", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tablesList.isSortingEnabled()
        self.tablesList.setSortingEnabled(False)
        self.tablesList.item(0).setText(QtGui.QApplication.translate("Dialog", "schema1.table1 AS t_1", None, QtGui.QApplication.UnicodeUTF8))
        self.tablesList.item(1).setText(QtGui.QApplication.translate("Dialog", "schema2.view2 AS v_1", None, QtGui.QApplication.UnicodeUTF8))
        self.tablesList.setSortingEnabled(__sortingEnabled)
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_1), QtGui.QApplication.translate("Dialog", "1. FROM TABLES", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsTree.headerItem().setText(0, QtGui.QApplication.translate("Dialog", "All Fields", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.fieldsTree.isSortingEnabled()
        self.fieldsTree.setSortingEnabled(False)
        self.fieldsTree.topLevelItem(0).setText(0, QtGui.QApplication.translate("Dialog", "schema1.table1 AS t_1", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsTree.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("Dialog", "field1", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsTree.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("Dialog", "field2", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsTree.topLevelItem(0).child(2).setText(0, QtGui.QApplication.translate("Dialog", "field3", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsTree.topLevelItem(1).setText(0, QtGui.QApplication.translate("Dialog", "schema2.view2 AS v_1", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsTree.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("Dialog", "field4", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsTree.topLevelItem(1).child(1).setText(0, QtGui.QApplication.translate("Dialog", "field5", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsTree.setSortingEnabled(__sortingEnabled)
        self.inFieldBtn.setText(QtGui.QApplication.translate("Dialog", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.outFieldBtn.setText(QtGui.QApplication.translate("Dialog", "<<", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.fieldsList.isSortingEnabled()
        self.fieldsList.setSortingEnabled(False)
        self.fieldsList.item(0).setText(QtGui.QApplication.translate("Dialog", "t_1.field2", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsList.item(1).setText(QtGui.QApplication.translate("Dialog", "v_1.field4", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsList.item(2).setText(QtGui.QApplication.translate("Dialog", "v_1.field5", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsList.setSortingEnabled(__sortingEnabled)
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("Dialog", "2. RETURNED FIELDS", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsCondTree.headerItem().setText(0, QtGui.QApplication.translate("Dialog", "All Fields", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.fieldsCondTree.isSortingEnabled()
        self.fieldsCondTree.setSortingEnabled(False)
        self.fieldsCondTree.topLevelItem(0).setText(0, QtGui.QApplication.translate("Dialog", "schema1.table1 AS t_1", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsCondTree.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("Dialog", "field1", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsCondTree.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("Dialog", "field2", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsCondTree.topLevelItem(0).child(2).setText(0, QtGui.QApplication.translate("Dialog", "field3", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsCondTree.topLevelItem(1).setText(0, QtGui.QApplication.translate("Dialog", "schema2.view2 AS v_1", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsCondTree.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("Dialog", "field4", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsCondTree.topLevelItem(1).child(1).setText(0, QtGui.QApplication.translate("Dialog", "field5", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsCondTree.setSortingEnabled(__sortingEnabled)
        self.eqBtn.setText(QtGui.QApplication.translate("Dialog", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.ltBtn.setText(QtGui.QApplication.translate("Dialog", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.gtBtn.setText(QtGui.QApplication.translate("Dialog", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.inBtn.setText(QtGui.QApplication.translate("Dialog", "IN", None, QtGui.QApplication.UnicodeUTF8))
        self.neqBtn.setText(QtGui.QApplication.translate("Dialog", "!=", None, QtGui.QApplication.UnicodeUTF8))
        self.lteBtn.setText(QtGui.QApplication.translate("Dialog", "<=", None, QtGui.QApplication.UnicodeUTF8))
        self.gteBtn.setText(QtGui.QApplication.translate("Dialog", ">=", None, QtGui.QApplication.UnicodeUTF8))
        self.ninBtn.setText(QtGui.QApplication.translate("Dialog", "NOT IN", None, QtGui.QApplication.UnicodeUTF8))
        self.andBtn.setText(QtGui.QApplication.translate("Dialog", "AND", None, QtGui.QApplication.UnicodeUTF8))
        self.orBtn.setText(QtGui.QApplication.translate("Dialog", "OR", None, QtGui.QApplication.UnicodeUTF8))
        self.notBtn.setText(QtGui.QApplication.translate("Dialog", "NOT", None, QtGui.QApplication.UnicodeUTF8))
        self.likeBtn.setText(QtGui.QApplication.translate("Dialog", "LIKE", None, QtGui.QApplication.UnicodeUTF8))
        self.ilikeBtn.setText(QtGui.QApplication.translate("Dialog", "ILIKE", None, QtGui.QApplication.UnicodeUTF8))
        self.percBtn.setText(QtGui.QApplication.translate("Dialog", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.inValueBtn.setText(QtGui.QApplication.translate("Dialog", "insert", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("Dialog", "3. WHERE CONDITION", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Query and columns you want to use to load a new layer", None, QtGui.QApplication.UnicodeUTF8))
        self.queryBrowser.setPlainText(QtGui.QApplication.translate("Dialog", "SELECT ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Geometry column:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Column with unique \n"
"integer values:", None, QtGui.QApplication.UnicodeUTF8))
        self.getColumnsBtn.setText(QtGui.QApplication.translate("Dialog", "Retrieve \n"
"columns", None, QtGui.QApplication.UnicodeUTF8))
        self.clearBtn.setText(QtGui.QApplication.translate("Dialog", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.saveQueryCheck.setText(QtGui.QApplication.translate("Dialog", "Save the query as", None, QtGui.QApplication.UnicodeUTF8))

